[package]
name = "planetarium"
version = "0.1.0"
edition = "2024"
rust-version = "1.93"
authors = ["Oleg Alexandrov <alexandrovoleg.ru@gmail.com>"]
readme = "README.md"
description = "A planetarium simulation built with Bevy game engine."
license = "MIT"
homepage = "https://teratron.github.io/planetarium"
documentation = "https://teratron.github.io/planetarium/docs"
repository = "https://github.com/teratron/planetarium"
keywords = ["rust", "bevy", "game", "simulation", "planetarium"]
categories = ["games", "simulation"]
exclude = ["examples/*", "docs/*", "tests/*", "target/*"]

[lib]
name = "planetarium"
path = "src/lib.rs"

[[bin]]
name = "planetarium"
path = "src/main.rs"

[dependencies]
bevy = "0.18.0"
toml = "0.9.11"
clap = { version = "4.5.1", features = ["derive"] }

[dev-dependencies]
dotenvy = "0.15.7"

[workspace]
resolver = "2"
members = ["examples/*"]

[[example]]
name = "hello"
path = "examples/hello.rs"
doc-scrape-examples = false

[package.metadata.example.hello]
name = "Hello"
description = "A quick start guide example demonstrating the basic features."
category = "Getting Started Guide"
wasm = false
