# Planetarium Asset Manifest
# Defines all mandatory assets for the application.

[fonts]
main = "fonts/FiraSans-Regular.ttf"
bold = "fonts/FiraSans-Regular.ttf"

[audio]
click = "audio/click.ogg"
hover = "audio/select.ogg"
music_menu = "audio/open.ogg"

[branding]
splash_logo = "images/logo_planetarium.png"
background_menu = "images/logo_planetarium.png"
